travis:
  secure:
    BINSTAR_TOKEN: z0becs25IsKXL0HqMoC4MhxLhuaCFBJj3c7VLsHbDxZGy3dsS6iYjKjndXGI0FecYViCh0yt0E5Tw0XLJ7K5umnEB/LxNsK8Dp/x4Ma8yBQIrzQE2pyziosabXdPYsvSDFzYZMTu/HSKa55nSha6aC4d58iVHl2DhCaO6bLYHVOGNvX7FcdnAh602rBygoDXab3BNFf4CIPrsX2jAS0+JNsM5MlpDAcoKkEDSxI/fHiXg97rDqUvfKK4CbOhIk67PbE8VoZeIid2f5qObLJW3lA9BCeoK23dqVMaml6nw6K88+8JBsVaCUPQOHGD7Bg1WFDz0fUtCct9DkrzccvHEZ4j/409P1dHbdsTM6Fn/bpwOSO7PzQ8enXPIB7gKTvwSFMJ86e5qVXRVs21MpR9ONcMm0n+7wZyzKAILAduW81eXmAbci6jdWRuLlOzQBz3rFe0bSyo5JpdIPxZXe7LqoC9FaIoaHR8OQL+ABtbZSZrlWXCFgtYPpRejtJ+PkkUonyKgfmt1p+SJNCym2XQNLuT4fzrn51OZayA0TydB/hLCMk3I3sQMfycM+L/iJ61He5yiQcn24kTvDLndvpg0yNfQZQDBh0d6+WLJ44iY48YDoQzMJAVf32kH9yYi9vOeT0xGFmRWxP1pIJfxFVp1exxJNOgR6sT4HAW8CZajCA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: appveyor
